## CI/CD
name: Promotion
run-name: Promotion ${{ inputs.promotion-type }} on ${{ inputs.schema-type }} ${{ inputs.uiconf-new-version }}

on:
  workflow_dispatch:
    inputs:
      promotion-type:
        type: choice
        required: true
        description: "from - to"
        options:
          - "qa --> qa-beta"
          - "qa-beta --> prod-beta"
          - "prod-beta --> prod-latest"
      schema-type:
        type: choice
        required: true
        description: "schema-type - example: 'playerV3Versions/playerV3OvpVersions'"
        options:
          - "playerV3Versions"
      uiconf-new-version:
        type: string
        required: false
        description: "not required - if no value is given it will increment the minor version - example 'from 1.00 to 1.01'"

jobs:
  promotion:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_promote.yaml@master
    secrets:
      CENTRAL_ACCOUNT_ID: ${{ secrets.CENTRAL_ACCOUNT_ID }}
      SERVICES_ACCOUNT_ID: ${{ secrets.SERVICES_ACCOUNT_ID }}
      S3_BUCKET_DEPLOYMENT: ${{ secrets.S3_BUCKET_DEPLOYMENT }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
      MSTEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}
    with:
      promotion-type: ${{ inputs.promotion-type }}
      schema-type: ${{ inputs.schema-type }}
      uiconf-new-version: ${{ inputs.uiconf-new-version }}

