name: Build NPM Package
run-name: Build NPM Package

on:
  workflow_call:
    inputs:
      node-version:
        description: "which node version to use - example: '17.x/18.x'"
        required: false
        type: string
        default: 16.13.0
      build-command:
        description: "which build command to run - example: 'npm run build'"
        required: false
        type: string
        default: build

jobs:
  get-standalone-commit:
    runs-on: ubuntu-latest
    outputs:
      standalone-commit: ${{ steps.get-commit.outputs.standalone-commit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          sparse-checkout: |
            kaltura-ws.json
          sparse-checkout-cone-mode: false
      - name: Get commit
        id: get-commit
        run: |
          COMMIT=$(jq -r '.commands.bookmark.standalone[]' kaltura-ws.json)
          echo "standalone-commit=${$COMMIT}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: get-standalone-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.get-standalone-commit.outputs.standalone-commit }}
      - name: Remove Node Modules
        run: rm -rf node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run ${{ inputs.build-command }}