name: Build NPM Package
run-name: Build NPM Package

on:
  workflow_call:
    inputs:
      node-version:
        description: "which node version to use - example: '17.x/18.x'"
        required: false
        type: string
        default: 16.13.0
      build-steps:
        description: "which build command to run - example: 'npm run build'"
        required: false
        type: string
        default: '["build"]'
      build-ref:
        description: "which ref to use for the build - example: 'main'"
        required: false
        type: string
        default: ${{ github.ref }}
      remove-node-modules:
        description: remove node_modules before build
        required: false
        type: boolean
        default: false
      build-output-dir:
        description: build output directory
        required: false
        type: string
        default: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.build-ref }}
      - name: Read NPM Package Info
        id: npm-package
        run:
          FILTER="name version"
          for i in $FILTER; do
            echo "$i=$(jq -r ".$i" package.json)" >> $GITHUB_OUTPUT
          done
          echo "full-name=$(jq -r ".name + \"-\" + .version" package.json)" >> $GITHUB_OUTPUT
      - name: Remove Node Modules
        if: ${{ inputs.remove-node-modules }}
        run: rm -rf node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install NPM Dependencies
        run: npm install
      - name: Build NPM Package
        run: echo "${{ inputs.build-steps }}" | jq -r '.[] | @sh' | xargs -I {} echo -c npm run {}
      - name: Zip Package
        run: |
          cd ${{ inputs.build-output-dir }}
          zip -r \
            ../${{ steps.npm-package.outputs.name }}-${{ steps.npm-package.outputs.version }}.zip
          cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.npm-package.outputs.full-name }}
          path: latest.zip
          retention-days: 1