name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  workflow_call:
    inputs:
      npm-install-list:
        description: "list of packages to overwrite in package.json - example: 'playkit-js/playkit-js@canary @playkit-js/playkit-js-dash@canary'"
        required: false
        type: string
      npm-run-to-execute:
        description: "list of package.json scripts - example: 'eslint flow test'"
        required: true
        type: string
      run-on-ubuntu:
        description: "run on ubuntu - example 'true/false'"
        required: false
        type: string
        default: 'true'
      enabled-openssl-legacy-provider:
        description: "enable the NODE_OPTIONS --openssl-legacy-provider - example: 'ture/false'"
        required: false
        type: string
        default: 'true'
      run-on-macos:
        description: "run on ubuntu - example 'true/false'"
        required: false
        type: string
        default: 'false'
      node-version:
        description: "which node version to use - example: '17.x/18.x'"
        required: false
        type: string
        default: '17.x'

jobs:
  set-matrix:
    runs-on: [ ubuntu-latest ]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set matrix
        id: set-matrix
        run: |
          if [ ${{ inputs.run-on-ubuntu }} = 'true' ] && [ ${{ inputs.run-on-macos }} = 'true' ]; then
            echo "matrix=[\"ubuntu-latest\",\"macos-latest\"]" >> $GITHUB_OUTPUT
          elif [ ${{ inputs.run-on-ubuntu }} = 'true' ]; then
            echo "matrix=[\"ubuntu-latest\"]" >> $GITHUB_OUTPUT
          elif [ ${{ inputs.run-on-macos }} = 'true' ]; then
            echo "matrix=[\"macos-latest\"]" >> $GITHUB_OUTPUT
          else
            "matrix=[]" >> $GITHUB_OUTPUT
          fi

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create temporary .npmrc
        run: |
          echo "@kaltura:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=\${GIT_TOKEN}" >> .npmrc
      - name: Preinstall
        run: npx --yes --prefer-online --registry=https://npm.pkg.github.com --package @kaltura/kaltura-tools@latest kaltura-tools check --root=.
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove temporary .npmrc
        run: rm -f .npmrc

  running-tests:
    needs: [set-matrix, prepare]
    strategy:
      matrix:
        os: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js version ${{ inputs.node-version }}
        uses: Wandalen/wretry.action@v1.0.36
        with:
          action: actions/setup-node@v4
          with: |
            node-version: ${{ inputs.node-version }}
          attempt_limit: 3
          attempt_delay: 2000
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Setup Firefox
        if: matrix.os == 'ubuntu-latest'
        uses: browser-actions/setup-firefox@v1
      - name: NPM update/install ${{ inputs.npm-install-list }}
        if: ${{ inputs.npm-install-list }}
        run: |
          for command in ${{ inputs.npm-install-list }}; do
            # Using npm install with a specific version/tag is equivalent to yarn upgrade for a targeted package
            npm install $command --save
          done
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KALTURA_JFROG_TOKEN: ${{ steps.setup-jfrog.outputs.oidc-token }}

      # - name: Remove .npmrc # TODO why is this needed ?
      #   run: |
      #     if [ -f .npmrc ]; then
      #       echo "Removing .npmrc..."
      #       rm .npmrc
      #     else
      #       echo ".npmrc not found, skipping."
      #     fi
      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog
        env:
          JF_URL: https://kalturaa.jfrog.io
        with:
          oidc-provider-name: ovp-github-oidc
      - name: NPM install --verbose
        run: npm install --force --verbose
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KALTURA_JFROG_TOKEN: ${{ steps.setup-jfrog.outputs.oidc-token }}
      - name: NPM run ${{ inputs.npm-run-to-execute }} with NODE_OPTIONS
        if: ${{ inputs.enabled-openssl-legacy-provider == 'true' }}
        run: |
          for command in ${{ inputs.npm-run-to-execute }}; do
            npm run $command
          done
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KALTURA_JFROG_TOKEN: ${{ steps.setup-jfrog.outputs.oidc-token }}
      - name: NPM run ${{ inputs.npm-run-to-execute }} without NODE_OPTIONS
        if: ${{ inputs.enabled-openssl-legacy-provider != 'true' }}
        run: |
          for command in ${{ inputs.npm-run-to-execute }}; do
            npm run $command
          done
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KALTURA_JFROG_TOKEN: ${{ steps.setup-jfrog.outputs.oidc-token }}