name: Find Changed Repos
run-name: Find Changed Repos

on:
  workflow_call:

jobs:
  find-changed-repos:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Repositories that have changed
        run: |
          pkg_version() {
              echo $(node -p "require('./package.json').version;")
          }

          pkg_modified() {
              prev_version_commit=$(git log --oneline | fgrep "$(pkg_version)" | awk '{print $1}')
              echo $(git log --oneline $prev_version_commit..HEAD | egrep "(fix|feat)\((FEC|FEV)-\d+\):")
          }

          my_dir=$(pwd)
          while read line; do
            git clone https://github.com/${line}.git ${line} > /dev/null 2>&1
            cd ${line}
            if [[ -n "$(pkg_modified)" ]]; then
              echo "https://github.com/${line}"
            fi
            cd ${my_dir}
            rm -rf ${line}
            sleep 2
          done < player-dependencies.txt