name: Find Changed Repos
run-name: Find Changed Repos

on:
  workflow_call:
    secrets:
      PLAYER_GITHUB_BOT_TOKEN:
        required: true


jobs:
  find-changed-repos:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repositories that have changed
        run: |
          #!/bin/bash
          pkg_version() {
              echo $(node -p "require('./package.json').version;")
          }

          pkg_modified() {
              prev_version_commit=$(git log --oneline | fgrep "$(pkg_version)" | awk '{print $1}')
              echo $(git log --oneline $prev_version_commit..HEAD | egrep "(fix|feat)\((FEC|FEV)-\d+\):")
          }

          git clone https://${{ secrets.PLAYER_GITHUB_BOT_TOKEN }}@github.com/kaltura/playkit-js-ui.git kaltura/playkit-js-ui > /dev/null 2>&1
          cd kaltura/playkit-js-ui
          echo "dor"
          git log --oneline d6ff7ab..HEAD | egrep '(fix|feat)\((FEC|FEV)-\d+\):'
          echo "dor"

